name: HTML Audit
on: [push, pull_request]
jobs:
    audit:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install -g audit-export
      - name: Run Audit Export
        run: cd React/Section2/ && npm audit --json | audit-export > audit-report.json
      - name: Archive Audit Report
        uses: actions/upload-artifact@v2
        with:
          name: audit-report-v2
          path: ./audit-report.json
