name: HTML Audit
on: [push, pull_request]
jobs:
    audit:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install -g audit-export
      - name: Run Audit Export
        run: cd React/Section2/ && npm audit --json | npx audit-export -f html -o audit-report.html
      - name: Archive Audit Report
        uses: actions/upload-artifact@v3
        with:
          name: audit-report-v3
          path: ./React/Section2/audit-report.html
